### ISSUE TITLE
Add a LICENSE file

### ISSUE THREAD

**Issue by jpwhitemn** [edgexfoundry/security-secret-store#55]
Add a LICENSE file to the base of this repo per https://wiki.edgexfoundry.org/pages/viewpage.action?pageId=21823866

**Comment by jamesrgregg** [comment]
@jpwhitemn we have a resource that is willing to work this Issue.  Could I get access please to assign someone?

**Comment by jpwhitemn** [comment]
James - absolutely; we welcome new hands :)
This is a repo under the control of the Security WG which means we need @Ferriera approval.  He is back on Monday.I will ping him via email as well.
Jim

    On Friday, January 4, 2019, 3:49:44 PM CST, jamesrgregg <notifications@github.com> wrote:  
 
 
@jpwhitemn we have a resource that is willing to work this Issue. Could I get access please to assign someone?

**Comment by alain2sf** [comment]
@jamesrgregg and @jpwhitemn Always glad to have more resources!

I'm currently working on issues #53 and #54, the Xmas/NY break put a pause on these actions but I'll resume next Monday when back to work, as David.

So, I already took care of #55 as it was trivial, but didn't believe a PR was meaningful for just this one. instead I was meaning to include it with #53/#54 and then submit a new PR. Anyways, I have this covered in my workspace but I can surely manage, and don't mind if someone else wants to take care of #55 before I submit my next PR. 

Cheers.

**Comment by jamesrgregg** [comment]
@alain2sf thank you and no worries.  
We were looking for an easy opportunity for a first time committer. We will look for another good one for @lranjbar from the Intel team.

**Comment by alain2sf** [comment]
@jamesrgregg I'm sure there will be plenty soon ;) 

Welcome @lranjbar happy to have you on board. Don't forget to join our Security WG call every Wednesday 8AM PST. And Slack #security channel if you have questions or need assistance during your learning process. There are a few topics we could discuss later on then, to be able to break them down so you could start contributing/committing with easy opportunities. Stick around!

**Comment by lranjbar** [comment]
@alain2sf Sure thing, I join the Security WG in this upcoming Wednesday. I was just looking for simple things to do while I'm ramping up. :)

**Comment by alain2sf** [comment]
@lranjbar No worries ;) "see" you on Wednesday then.
