### ISSUE TITLE
package naming in glide.yaml

### ISSUE THREAD

**Issue by bnevis-i** [edgexfoundry/security-secret-store#56]
https://github.com/edgexfoundry/security-secret-store/blob/07983302c365473806144c925649e26f2e1e555b/glide.yaml#L1

Shouldn't this be github.com/edgexfoundry/security-secret-store?

**Comment by alain2sf** [comment]
I would think so, indeed. 
@anonymouse64 Hi Ian, does this Glide config works well without the full package path ?

**Comment by anonymouse64** [comment]
Aren't we going to transition to go modules eventually and get rid of glide? If so we can just ignore the warning here and switch to modules soon.

@tsconn23 is the transition to go modules for edgex-go happening for edinburgh or after?

**Comment by alain2sf** [comment]
@anonymouse64 @tsconn23 Similar question here, is the transition to go modules for security-* happening for Edinburgh or after ?

**Comment by anonymouse64** [comment]
I would say that if we do it for edgex-go we should also do it for the security-* repos.

**Comment by alain2sf** [comment]
Fair enough ;)  Targeted release is Edinburgh ?

**Comment by anonymouse64** [comment]
Yes next release is Edinburgh

**Comment by tingyuz** [comment]
closed the issue as we are moving on go-module currently.
