### ISSUE TITLE
Convert to Go Module

### ISSUE THREAD

**Issue by tsconn23** [edgexfoundry/security-secret-store#61]
This service needs to be converted to a Go module in order to eliminate the use of glide.

More information
https://github.com/golang/go/wiki/Modules#migrating-to-modules

If there is a current dependency on edgex-go in this service, that should be refactored to instead use https://github.com/edgexfoundry/go-mod-core-contracts

**Comment by lenny-goodell** [comment]
Jim Wang (jim-wang-intel) from our team will take this one

**Comment by jim-wang-yutsung** [comment]
@tsconn23 & @jpwhitemn the security-api-gateway is now in go-module, this issue should be in verified state and can be closed.

**Comment by tingyuz** [comment]
The project is in Go-module now so close the ticket.
